import { Article, BrainTeaser, Category, Horoscope, Joke, Quote, YouTubeVideo } from "./types"

// Categories data
export const categories: Category[] = [
  {
    id: "tech",
    name: "Tech & AI",
    description: "Latest news in technology and artificial intelligence",
    icon: "cpu",
  },
  {
    id: "health",
    name: "Health",
    description: "Tips and news for a healthier lifestyle",
    icon: "heart",
  },
  {
    id: "stocks",
    name: "Stocks",
    description: "Market trends and financial updates",
    icon: "trending-up",
  },
  {
    id: "horoscope",
    name: "Horoscope",
    description: "Daily astrological predictions",
    icon: "star",
  },
  {
    id: "quotes",
    name: "Quotes",
    description: "Inspirational and motivational quotes",
    icon: "quote",
  },
  {
    id: "jokes",
    name: "Jokes",
    description: "Daily dose of humor to brighten your day",
    icon: "smile",
  },
  {
    id: "brainteasers",
    name: "Brain Teasers",
    description: "Puzzles and mind games to challenge your brain",
    icon: "brain",
  },
  {
    id: "videos",
    name: "Videos",
    description: "Trending videos across various categories",
    icon: "video",
  },
]

// Sample Articles for Tech & AI
export const techArticles: Article[] = [
  {
    id: "1",
    title: "The Future of AI: Transforming How We Live and Work",
    summary: "AI advancements are rapidly changing industries and daily life. Here's what to expect in the coming years.",
    content: "Artificial Intelligence continues to evolve at an unprecedented pace, transforming industries from healthcare to finance. Recent breakthroughs in deep learning and neural networks have opened new possibilities for automated systems that can reason, learn, and adapt with minimal human intervention. As these technologies mature, we're seeing applications that range from autonomous vehicles to AI-powered diagnostic tools in medicine.\n\nExperts predict that the next wave of AI innovation will focus on making these systems more transparent and explainable, addressing concerns about 'black box' algorithms. Additionally, there's growing interest in developing AI systems that can operate effectively with smaller datasets, reducing the massive data requirements that currently limit deployment in some fields.\n\nFor the average person, these changes will manifest in more intuitive digital assistants, smarter home systems, and personalized services that anticipate needs before they're expressed. However, these advances also raise important questions about privacy, security, and the changing nature of work in an AI-augmented world.",
    category: "tech",
    tags: ["AI", "Future Tech", "Innovation"],
    readTime: 8,
    date: "2023-05-15",
    imageUrl: "https://images.pexels.com/photos/8386434/pexels-photo-8386434.jpeg",
    source: "medium.com",
  },
  {
    id: "2",
    title: "TypeScript 5.0: What Developers Need to Know",
    summary: "The latest TypeScript update brings significant improvements to decorator support and performance optimizations.",
    content: "TypeScript 5.0 represents a significant milestone for Microsoft's popular typed superset of JavaScript. This major release brings long-awaited improvements to decorators, making them more aligned with the JavaScript proposal currently at stage 3 in the TC39 process. The new implementation is simpler, more flexible, and addresses many of the limitations developers faced with experimental decorators.\n\nPerformance was another focus area, with the TypeScript team reporting up to 40% faster compile times for certain projects. This was achieved through internal restructuring and more efficient type checking algorithms. Memory usage has also been significantly reduced, which is particularly beneficial for large-scale enterprise applications.\n\nThe new 'const' type parameters feature adds more flexibility for working with literal types, allowing developers to write more type-safe code when dealing with object literals and tuple types. Additionally, several quality-of-life improvements such as better error messages and enhanced auto-completion make the developer experience more pleasant.\n\nFor teams considering an upgrade, the breaking changes are relatively minor, but the benefits in terms of performance and new features make a compelling case for adoption.",
    category: "tech",
    tags: ["TypeScript", "JavaScript", "Programming"],
    readTime: 6,
    date: "2023-05-10",
    imageUrl: "https://images.pexels.com/photos/4164418/pexels-photo-4164418.jpeg",
    source: "dev.to",
  },
  {
    id: "3",
    title: "Web Development Trends That Will Dominate 2023",
    summary: "From headless CMS to WebAssembly, these are the technologies shaping the future of web development.",
    content: "As web technologies continue to evolve at a rapid pace, staying ahead of the curve is essential for developers and businesses alike. Several key trends are emerging as game-changers for 2023 and beyond.\n\nHeadless architecture continues to gain momentum, with more companies separating their front-end presentation layer from back-end functionality. This approach offers greater flexibility, improved performance, and better content reusability across different platforms and devices. Leading the charge are headless CMS solutions that provide robust APIs for content delivery while giving developers freedom to choose their preferred front-end technologies.\n\nWebAssembly (Wasm) is finally seeing widespread adoption, enabling high-performance applications in the browser that were previously impossible. From browser-based video editing to complex data visualization and games, Wasm is opening new possibilities for web applications that rival desktop software in functionality and responsiveness.\n\nThe Jamstack architecture (JavaScript, APIs, and Markup) continues to evolve, with new tools making it even more powerful. Static site generators and incremental static regeneration capabilities are bringing the best of both worlds: the security and performance of static sites with the dynamic capabilities traditionally associated with server-rendered applications.\n\nMicro-frontends are gaining traction for large-scale applications, allowing teams to work independently on different parts of an application while maintaining a cohesive user experience. This architectural approach mirrors the successful microservices pattern on the backend, bringing similar benefits to frontend development.",
    category: "tech",
    tags: ["Web Development", "Trends", "Programming"],
    readTime: 7,
    date: "2023-05-08",
    imageUrl: "https://images.pexels.com/photos/7775642/pexels-photo-7775642.jpeg",
    source: "medium.com",
  },
  {
    id: "4",
    title: "Quantum Computing: Are We at the Tipping Point?",
    summary: "Recent breakthroughs suggest quantum computing may be ready for practical applications sooner than expected.",
    content: "The field of quantum computing has reached what many experts consider a critical inflection point. After decades of theoretical work and laboratory demonstrations, quantum systems are beginning to show practical advantages over classical computers for specific problems. IBM, Google, and several startups have made significant strides in reducing error rates and increasing the coherence time of qubits, two of the main obstacles to practical quantum computing.\n\nIBM's recent announcement of their 433-qubit Osprey processor represents more than just a numerical increase from their previous 127-qubit Eagle chip. The company has made significant improvements in reducing noise and improving gate fidelity, making these qubits more useful for real-world applications. Similarly, Google's quantum team has reported success with error correction techniques that may pave the way for fault-tolerant quantum computing.\n\nWhile a general-purpose quantum computer that can crack modern encryption remains a distant goal, the near-term applications in materials science, drug discovery, and optimization problems are looking increasingly viable. Companies in the pharmaceutical and financial sectors are already running experiments on today's noisy intermediate-scale quantum (NISQ) devices, preparing for the quantum advantage expected in specific domains within the next 3-5 years.\n\nFor software developers, quantum programming libraries and cloud access to quantum hardware are making it easier to experiment and build quantum-ready applications. Languages and frameworks like Qiskit, Cirq, and Q# are maturing, with growing communities and educational resources.",
    category: "tech",
    tags: ["Quantum Computing", "Future Tech", "Innovation"],
    readTime: 9,
    date: "2023-05-05",
    imageUrl: "https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg",
    source: "medium.com",
  },
]

// Sample Articles for Health
export const healthArticles: Article[] = [
  {
    id: "5",
    title: "Mediterranean Diet Linked to Lower Risk of Cognitive Decline",
    summary: "New research confirms the benefits of this eating pattern for brain health as we age.",
    content: "A comprehensive study spanning 12 years and involving over 6,000 participants has provided strong evidence that following a Mediterranean diet is associated with significantly reduced risk of cognitive decline and dementia. The research, published in the journal Neurology, showed that participants who most closely adhered to the diet had up to 23% lower risk of developing cognitive impairment compared to those who followed it least closely.\n\nThe Mediterranean diet, characterized by high consumption of vegetables, fruits, legumes, nuts, whole grains, fish, and olive oil, has long been associated with cardiovascular benefits. This new research suggests its protective effects extend to brain health, possibly due to reduced inflammation and improved vascular function.\n\nDr. Maria Lopez, the lead researcher, noted that the diet's combined effects appear to be greater than any single component. 'It's the pattern of eating rather than any one food that seems to confer protection,' she explained. 'The various components of the Mediterranean diet work synergistically to reduce oxidative stress and inflammation throughout the body, including the brain.'\n\nParticularly notable was the finding that it's never too late to benefit from dietary changes. Participants who improved their adherence to the Mediterranean pattern during the study period showed cognitive benefits even if they hadn't been following the diet earlier in life.",
    category: "health",
    tags: ["Nutrition", "Brain Health", "Aging"],
    readTime: 7,
    date: "2023-05-12",
    imageUrl: "https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg",
    source: "healthline.com",
  },
  {
    id: "6",
    title: "The Science of Sleep: How Much Do You Really Need?",
    summary: "Research reveals that quality matters as much as quantity when it comes to rest.",
    content: "Sleep science has evolved dramatically in recent years, challenging some long-held assumptions about how much sleep we need and what constitutes healthy sleep patterns. The National Sleep Foundation recently updated its guidelines after a comprehensive review of over 300 scientific studies, introducing more nuanced recommendations based on age, lifestyle, and individual variation.\n\nWhile the widely-cited eight-hour recommendation remains a good average target for adults, research now emphasizes that sleep needs vary significantly between individuals. Genetic factors play a substantial role, with some people functioning optimally on seven hours while others genuinely require nine or more hours. What's more important than hitting a specific number is consistency and quality of sleep.\n\nDr. Matthew Walker, a leading sleep researcher, emphasizes that quality indicators such as sleep continuity, the proportion of REM and deep NREM sleep, and how refreshed one feels upon waking are more predictive of health outcomes than total hours alone. 'The architecture of sleep matters tremendously,' Walker explains. 'Six hours of high-quality, uninterrupted sleep can be more restorative than eight hours of fragmented sleep.'\n\nRecent studies have also challenged the notion that humans naturally sleep in one consolidated block. Historical evidence suggests that before electric lighting, many people slept in two distinct phases separated by a period of wakefulness in the middle of the night. This 'biphasic' pattern may be more natural for some individuals than forcing a single eight-hour block.",
    category: "health",
    tags: ["Sleep", "Wellness", "Health Research"],
    readTime: 6,
    date: "2023-05-09",
    imageUrl: "https://images.pexels.com/photos/3771069/pexels-photo-3771069.jpeg",
    source: "webmd.com",
  },
  {
    id: "7",
    title: "High-Intensity Interval Training: Benefits Beyond Weight Loss",
    summary: "HIIT workouts offer surprising cognitive and metabolic advantages, new study finds.",
    content: "High-Intensity Interval Training (HIIT) has gained popularity primarily as an efficient way to burn calories and improve cardiovascular fitness, but emerging research points to benefits that extend far beyond weight management. A groundbreaking study published in the Journal of Physiology demonstrates that HIIT may trigger unique cellular responses that benefit brain health and metabolic function in ways that moderate, steady-state exercise does not.\n\nThe research team, led by Dr. James Peterson, measured various biomarkers in participants who completed either 30 minutes of moderate-intensity continuous training or 10 minutes of HIIT (including warm-up and cool-down) three times per week for eight weeks. While both groups showed improvements in cardiovascular fitness, the HIIT group demonstrated significantly greater increases in brain-derived neurotrophic factor (BDNF), a protein associated with cognitive function and neuroplasticity.\n\n'What surprised us most was the magnitude of difference in certain neurological markers,' Peterson explained. 'The brief, intense nature of HIIT appears to trigger a cascade of signaling mechanisms that promote brain health in addition to the cardiovascular benefits we expected.'\n\nAdditionally, the HIIT group showed more substantial improvements in insulin sensitivity and mitochondrial function in muscle cells, suggesting this form of exercise may be particularly beneficial for metabolic health and potentially reducing the risk of type 2 diabetes.",
    category: "health",
    tags: ["Exercise", "Fitness", "Brain Health"],
    readTime: 5,
    date: "2023-05-07",
    imageUrl: "https://images.pexels.com/photos/3658377/pexels-photo-3658377.jpeg",
    source: "healthline.com",
  },
  {
    id: "8",
    title: "The Gut-Brain Connection: How Your Microbiome Affects Mental Health",
    summary: "Scientists are uncovering how the bacteria in your digestive system influence mood and cognitive function.",
    content: "The relationship between gut health and mental wellbeing has emerged as one of the most fascinating areas of medical research in recent years. Often referred to as the 'gut-brain axis,' this bidirectional communication system links emotional and cognitive centers of the brain with peripheral intestinal functions. Recent studies have revealed that the trillions of bacteria inhabiting our digestive systems—collectively known as the gut microbiome—play a crucial role in this connection.\n\nResearch published in Nature Neuroscience demonstrated that certain gut bacteria species produce neurotransmitters such as serotonin, dopamine, and GABA—the same chemicals that regulate mood in the brain. In fact, approximately 95% of the body's serotonin is produced in the gut, not the brain, highlighting the importance of digestive health for emotional wellbeing.\n\nClinical studies are now showing promising results for interventions targeting the microbiome. A randomized controlled trial at Oxford University found that a specific probiotic formulation significantly reduced symptoms of depression compared to placebo. Similarly, dietary interventions that increase microbiome diversity through plant-based foods rich in prebiotics have shown positive effects on stress resilience and anxiety levels.\n\nDr. Michael Gershon, author of 'The Second Brain,' explains that the enteric nervous system—the complex network of neurons embedded in the gut wall—contains more neurons than the spinal cord. 'We've long underestimated how sophisticated the gut's nervous system is and how it influences our mental states,' Gershon notes. 'The gut is constantly sending signals to the brain that affect everything from appetite to emotional processing.'",
    category: "health",
    tags: ["Gut Health", "Mental Health", "Microbiome"],
    readTime: 8,
    date: "2023-05-02",
    imageUrl: "https://images.pexels.com/photos/3683098/pexels-photo-3683098.jpeg",
    source: "webmd.com",
  },
]

// Sample Articles for Stocks
export const stockArticles: Article[] = [
  {
    id: "9",
    title: "Market Volatility: Strategies for Uncertain Times",
    summary: "Financial experts share approaches for navigating turbulent market conditions.",
    content: "Market volatility has increased significantly in recent months, driven by concerns about inflation, interest rate hikes, and geopolitical tensions. For investors, this uncertainty presents both challenges and opportunities that require thoughtful strategy adjustments.\n\nFinancial advisors are emphasizing the importance of portfolio diversification beyond the traditional stock-bond mix. Alternative assets such as real estate investment trusts (REITs), commodities, and inflation-protected securities are gaining prominence as hedges against both inflation and market downturns. 'The old 60/40 portfolio may not provide the protection it once did when both stocks and bonds are under pressure from the same macroeconomic forces,' explains Janet Rodriguez, Chief Investment Strategist at Capital Advisors.\n\nDollar-cost averaging—the practice of investing a fixed amount at regular intervals regardless of market conditions—has proven effective during volatile periods. This approach removes the emotional element from investment decisions and takes advantage of price dips without requiring perfect market timing.\n\nFor those approaching retirement, reassessing risk tolerance and liquidity needs has become critical. Creating a 'stability bucket' with 1-2 years of living expenses in cash or cash equivalents can provide peace of mind and prevent forced selling during market downturns.\n\nCounter-intuitively, some financial planners are advising against overly defensive positioning. 'The worst investment decisions are often made out of fear,' notes Richard Chen, CFP. 'Historical data shows that markets often deliver their strongest returns amid periods of maximum pessimism.'",
    category: "stocks",
    tags: ["Investing", "Market Strategy", "Financial Planning"],
    readTime: 7,
    date: "2023-05-14",
    imageUrl: "https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg",
    source: "finance.yahoo.com",
  },
  {
    id: "10",
    title: "Tech Sector Analysis: Where to Invest After the Correction",
    summary: "Following significant pullbacks, certain technology subsectors now offer compelling valuations.",
    content: "The technology sector has experienced a significant correction over the past year, with many former high-flyers seeing their valuations cut by 50% or more. This repricing has created potential opportunities for discerning investors who can distinguish between companies with temporary challenges and those facing fundamental disruption.\n\nSemiconductor stocks, despite ongoing supply chain concerns, have shown remarkable resilience in their underlying business fundamentals. Companies involved in chip manufacturing for artificial intelligence, data centers, and automotive applications are reporting record order backlogs that extend multiple quarters into the future. Analysts at Morgan Stanley highlight that the sector is trading at approximately 16 times forward earnings, below its five-year average of 18.5, despite stronger long-term growth prospects driven by AI, edge computing, and the Internet of Things.\n\nEnterprise software companies that have transitioned successfully to recurring revenue models present another area of interest. While growth rates have moderated from pandemic highs, businesses continue to prioritize digital transformation initiatives, maintaining robust demand for cloud infrastructure, cybersecurity, and data analytics solutions. Companies with high gross margins, strong cash flow, and mission-critical products have demonstrated pricing power even in an inflationary environment.\n\nIn contrast, consumer-facing technology companies face more significant challenges as digital advertising budgets tighten and e-commerce growth normalizes after the pandemic surge. Regulatory headwinds and privacy changes have also impacted business models that rely heavily on targeted advertising and user data monetization.",
    category: "stocks",
    tags: ["Tech Stocks", "Investing", "Market Analysis"],
    readTime: 8,
    date: "2023-05-11",
    imageUrl: "https://images.pexels.com/photos/6802042/pexels-photo-6802042.jpeg",
    source: "moneycontrol.com",
  },
  {
    id: "11",
    title: "ESG Investing: Performance Metrics and Future Outlook",
    summary: "Environmental, Social, and Governance factors increasingly influence investment decisions and returns.",
    content: "Environmental, Social, and Governance (ESG) investing has evolved from a niche approach to a mainstream investment consideration, with global ESG assets expected to exceed $50 trillion by 2025, representing more than a third of projected total assets under management. However, the sector is experiencing growing pains as investors demand more rigorous performance metrics and standardized reporting frameworks.\n\nA comprehensive analysis by Morningstar of 4,900 sustainable funds found that 52% outperformed their traditional counterparts over the past five years, with particularly strong results in European and emerging markets. The outperformance was most notable during market downturns, suggesting that companies with strong ESG profiles may be more resilient during periods of stress.\n\nSectoral differences in ESG performance have been substantial. Funds focused on renewable energy and clean technology have shown significant volatility, with exceptional returns in 2020 followed by underperformance in 2021-2022 as interest rates rose. In contrast, funds emphasizing corporate governance and social factors delivered more consistent results across different market environments.\n\nRegulatory developments are reshaping the ESG landscape. The European Union's Sustainable Finance Disclosure Regulation (SFDR) has established a classification system that requires funds to categorize themselves based on the extent to which sustainability is incorporated into their investment process. Similar regulations are being developed in the United States, with the SEC proposing mandatory climate risk disclosures for public companies.",
    category: "stocks",
    tags: ["ESG", "Sustainable Investing", "Market Trends"],
    readTime: 6,
    date: "2023-05-06",
    imageUrl: "https://images.pexels.com/photos/2422294/pexels-photo-2422294.jpeg",
    source: "finance.yahoo.com",
  },
  {
    id: "12",
    title: "Global Inflation and Central Bank Policies: Impact on Markets",
    summary: "How monetary policy shifts are affecting different asset classes and investment strategies.",
    content: "Central banks worldwide are navigating the challenging task of taming inflation without triggering a recession, creating significant implications for financial markets across all asset classes. The coordinated tightening cycle, led by the Federal Reserve's aggressive interest rate hikes, represents a fundamental shift in the monetary environment that has supported asset prices for over a decade.\n\nEquity markets are adjusting to this new reality through a process of valuation compression, with price-to-earnings ratios declining across most sectors. Companies with strong pricing power, healthy balance sheets, and the ability to pass increased costs to consumers have demonstrated greater resilience. Value stocks, which typically outperform during inflationary periods and rising interest rate environments, have seen renewed investor interest after years of underperformance relative to growth stocks.\n\nFixed income markets have experienced historic volatility, with the Bloomberg Global Aggregate Bond Index recording its worst performance in decades. Investment strategies are evolving in response, with a greater emphasis on active management, shorter duration portfolios, and floating-rate instruments. Corporate credit spreads have widened, creating opportunities in select high-quality bonds that now offer attractive yields relative to historical norms.\n\nCurrency markets reflect divergent monetary policies, with the U.S. dollar strengthening against most currencies as the Federal Reserve leads the tightening cycle. This dollar strength creates headwinds for emerging markets with dollar-denominated debt but benefits U.S. consumers through improved purchasing power for imported goods.",
    category: "stocks",
    tags: ["Inflation", "Central Banks", "Monetary Policy"],
    readTime: 9,
    date: "2023-05-03",
    imageUrl: "https://images.pexels.com/photos/534216/pexels-photo-534216.jpeg",
    source: "moneycontrol.com",
  },
]

// Sample Horoscopes
export const horoscopes: Horoscope[] = [
  {
    id: "13",
    title: "Aries Daily Horoscope",
    summary: "An unexpected opportunity may arise in your professional life today.",
    date: "2023-05-15",
    sign: "Aries",
    prediction: "Today brings a surge of energy that serves you well in tackling long-standing projects. Your natural leadership qualities shine, making this an excellent day to take initiative on team endeavors. An unexpected opportunity may arise in your professional life—trust your instincts about whether to pursue it. In personal relationships, practice patience as not everyone will match your pace today. Tonight favors social connections, so consider accepting that invitation you've been pondering.",
    imageUrl: "https://images.pexels.com/photos/1809644/pexels-photo-1809644.jpeg",
  },
  {
    id: "14",
    title: "Taurus Daily Horoscope",
    summary: "Focus on stability and practical matters today, especially financial planning.",
    date: "2023-05-15",
    sign: "Taurus",
    prediction: "The planetary alignment today encourages you to focus on stability and practical matters. It's an excellent time for financial planning or making important decisions about your material security. Your natural persistence will help you overcome any obstacles that arise. In relationships, your loyalty is appreciated, but ensure you're not being stubborn about trivial matters. Creative pursuits are favored in the evening hours, offering a pleasant balance to the day's pragmatic focus.",
    imageUrl: "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg",
  },
  {
    id: "15",
    title: "Gemini Daily Horoscope",
    summary: "Your communication skills are especially sharp today, helping resolve misunderstandings.",
    date: "2023-05-15",
    sign: "Gemini",
    prediction: "Your communication skills are especially sharp today, Gemini, making this an ideal time to resolve any lingering misunderstandings. Information flows easily, and you may find yourself connecting dots that previously eluded you. While your mind is buzzing with ideas, try to focus on completing one task before jumping to the next. A conversation with a friend could lead to an exciting collaboration. Tonight, intellectual pursuits bring satisfaction—perhaps it's time to start that book you've been meaning to read.",
    imageUrl: "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg",
  },
  {
    id: "16",
    title: "Cancer Daily Horoscope",
    summary: "Emotional insights provide clarity about a personal relationship or family matter.",
    date: "2023-05-15",
    sign: "Cancer",
    prediction: "Today brings emotional insights that provide clarity about a personal relationship or family matter that's been on your mind. Your intuition is particularly strong—trust the subtle feelings guiding you. It's a favorable day for home improvements or creating a more nurturing environment in your personal space. Financial matters require attention; a careful review may reveal an opportunity for savings. Tonight, self-care should be prioritized—perhaps a relaxing bath or your favorite comfort food will provide the nurturing energy you need.",
    imageUrl: "https://images.pexels.com/photos/1809644/pexels-photo-1809644.jpeg",
  },
]

// Sample Quotes
export const quotes: Quote[] = [
  {
    id: "17",
    title: "On Perseverance",
    summary: "A powerful reminder about the value of persistence through difficult times.",
    date: "2023-05-15",
    author: "Winston Churchill",
    text: "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    category: "Motivation",
    imageUrl: "https://images.pexels.com/photos/3800516/pexels-photo-3800516.jpeg",
  },
  {
    id: "18",
    title: "On Growth",
    summary: "A perspective on how challenges shape our development and character.",
    date: "2023-05-15",
    author: "Friedrich Nietzsche",
    text: "That which does not kill us makes us stronger.",
    category: "Philosophy",
    imageUrl: "https://images.pexels.com/photos/1474993/pexels-photo-1474993.jpeg",
  },
  {
    id: "19",
    title: "On Imagination",
    summary: "A reflection on the limitless power of human creativity and imagination.",
    date: "2023-05-15",
    author: "Albert Einstein",
    text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.",
    category: "Creativity",
    imageUrl: "https://images.pexels.com/photos/7543641/pexels-photo-7543641.jpeg",
  },
  {
    id: "20",
    title: "On Action",
    summary: "A reminder that ideas must be paired with effort to create meaningful change.",
    date: "2023-05-15",
    author: "Leonardo da Vinci",
    text: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.",
    category: "Achievement",
    imageUrl: "https://images.pexels.com/photos/7292745/pexels-photo-7292745.jpeg",
  },
]

// Sample Jokes
export const jokes: Joke[] = [
  {
    id: "21",
    title: "Programming Logic",
    summary: "A humorous take on the precision required in programming.",
    date: "2023-05-15",
    text: "Why do programmers prefer dark mode? Because light attracts bugs!",
    category: "Tech Humor",
    imageUrl: "https://images.pexels.com/photos/879109/pexels-photo-879109.jpeg",
  },
  {
    id: "22",
    title: "Coffee Break",
    summary: "A joke about our dependence on caffeine in modern life.",
    date: "2023-05-15",
    text: "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    category: "Wordplay",
    imageUrl: "https://images.pexels.com/photos/1132577/pexels-photo-1132577.jpeg",
  },
  {
    id: "23",
    title: "Weather Report",
    summary: "A light-hearted joke about meteorological predictions.",
    date: "2023-05-15",
    text: "I was going to tell a joke about the weather, but it's probably a bit cloudy.",
    category: "Dad Jokes",
    imageUrl: "https://images.pexels.com/photos/3617457/pexels-photo-3617457.jpeg",
  },
  {
    id: "24",
    title: "Musical Note",
    summary: "A pun involving musical terminology that's sure to make you smile.",
    date: "2023-05-15",
    text: "What's Beethoven's favorite fruit? BA-NA-NA-NAAA!",
    category: "Music Jokes",
    imageUrl: "https://images.pexels.com/photos/4709822/pexels-photo-4709822.jpeg",
  },
]

// Sample Brain Teasers
export const brainTeasers: BrainTeaser[] = [
  {
    id: "25",
    title: "The Missing Dollar",
    summary: "A classic mathematical riddle that confuses even the sharpest minds.",
    date: "2023-05-15",
    question: "Three friends split the cost of a hotel room for $30. Later, the hotel manager realizes the room should have been $25 and sends a bellhop to return $5. The bellhop gives each person $1 and keeps $2 for himself. So each person paid $10 and got $1 back, meaning they each paid $9, totaling $27. The bellhop kept $2, and $27 + $2 = $29. Where's the missing dollar?",
    answer: "This is a misdirection puzzle. The correct calculation is: The friends paid $27 total ($9 each), $25 went to the hotel and $2 to the bellhop. That's $27 total. There is no missing dollar; the addition of the $27 and $2 is not a meaningful calculation.",
    difficulty: "medium",
    category: "Logic Puzzle",
    imageUrl: "https://images.pexels.com/photos/4021939/pexels-photo-4021939.jpeg",
  },
  {
    id: "26",
    title: "The Crossing River Challenge",
    summary: "A classic logic puzzle involving transporting items across a river with constraints.",
    date: "2023-05-15",
    question: "A farmer needs to cross a river with a wolf, a goat, and a cabbage. The boat is only big enough for the farmer and one item. If left alone, the wolf will eat the goat, and the goat will eat the cabbage. How can the farmer get everything across safely?",
    answer: "First, take the goat across. Return empty. Take the wolf across, bring the goat back. Take the cabbage across. Return empty. Finally, take the goat across. This ensures that the wolf and goat, or the goat and cabbage, are never left alone together.",
    difficulty: "medium",
    category: "Logic Puzzle",
    imageUrl: "https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg",
  },
  {
    id: "27",
    title: "The Monty Hall Problem",
    summary: "A famous probability puzzle that challenges our intuition about statistics.",
    date: "2023-05-15",
    question: "You're on a game show with three doors. Behind one is a car, behind the others are goats. You pick a door, say No. 1. The host, who knows what's behind each door, opens another door, say No. 3, revealing a goat. Should you switch to door No. 2 or stick with your original choice?",
    answer: "You should switch doors. When you initially choose, you have a 1/3 chance of picking the car. The host then eliminates one incorrect option. By switching, you win if your original choice was wrong (which happens 2/3 of the time). Therefore, switching gives you a 2/3 chance of winning, while staying gives you only a 1/3 chance.",
    difficulty: "hard",
    category: "Probability",
    imageUrl: "https://images.pexels.com/photos/3760810/pexels-photo-3760810.jpeg",
  },
  {
    id: "28",
    title: "Einstein's Riddle",
    summary: "A logic puzzle allegedly created by Albert Einstein that tests deductive reasoning.",
    date: "2023-05-15",
    question: "Five houses painted in different colors stand in a row. In each house lives a person of different nationality. Each person drinks a certain beverage, plays a certain sport, and keeps a certain pet. Using the given clues, determine who owns the fish: 1) The Brit lives in the red house. 2) The Swede keeps dogs. 3) The Dane drinks tea. 4) The green house is on the left of the white house. 5) The owner of the green house drinks coffee. 6) The person who plays polo rears birds. 7) The owner of the yellow house plays hockey. 8) The person living in the center house drinks milk. 9) The Norwegian lives in the first house. 10) The person who plays baseball lives next to the one who keeps cats. 11) The person who keeps horses lives next to the one who plays hockey. 12) The person who plays football drinks beer. 13) The German plays soccer. 14) The Norwegian lives next to the blue house. 15) The person who plays baseball has a neighbor who drinks water.",
    answer: "After working through all the clues systematically, the German owns the fish.",
    difficulty: "hard",
    category: "Logic Grid",
    imageUrl: "https://images.pexels.com/photos/3807639/pexels-photo-3807639.jpeg",
  },
]

// Sample YouTube Videos
export const youtubeVideos: YouTubeVideo[] = [
  {
    id: "29",
    title: "The Future of Artificial Intelligence",
    summary: "An in-depth look at how AI is transforming industries and what's coming next.",
    date: "2023-05-14",
    videoId: "5KWELtJZvRU",
    channelName: "TED",
    category: "Technology",
    viewCount: 1250000,
    imageUrl: "https://img.youtube.com/vi/5KWELtJZvRU/maxresdefault.jpg",
  },
  {
    id: "30",
    title: "10-Minute Morning Yoga for Energy",
    summary: "Start your day with this energizing yoga routine designed for beginners.",
    date: "2023-05-13",
    videoId: "UEEsdXn8oG8",
    channelName: "Yoga With Adriene",
    category: "Health",
    viewCount: 985000,
    imageUrl: "https://img.youtube.com/vi/UEEsdXn8oG8/maxresdefault.jpg",
  },
  {
    id: "31",
    title: "Understanding Market Volatility",
    summary: "A financial expert explains what causes market swings and how to navigate them.",
    date: "2023-05-12",
    videoId: "Xn7KWR9EOGQ",
    channelName: "Bloomberg",
    category: "Finance",
    viewCount: 456000,
    imageUrl: "https://img.youtube.com/vi/Xn7KWR9EOGQ/maxresdefault.jpg",
  },
  {
    id: "32",
    title: "The Science of Motivation",
    summary: "Psychological insights into what drives us and how to stay motivated.",
    date: "2023-05-10",
    videoId: "LL8Fa5pQEXY",
    channelName: "Vsauce",
    category: "Psychology",
    viewCount: 1783000,
    imageUrl: "https://img.youtube.com/vi/LL8Fa5pQEXY/maxresdefault.jpg",
  },
]